### PR TITLE
Open .csx from any location file using RoslynPad #222

### LINKED ISSUE #222: Open .csx from any location file using RoslynPad
Hello:)
When I run RoslynPad.exe, I want to open a specific .csx file and run it.
For example, when executing in command prompt, specify args.

in command prompt : 
>RoslynPad.exe D:\myroot\rosl.csx

How to open a  particular .csx file while running a RoslynPad.exe?

### PR DESCRIPTION
**Pull request by jiyeongj**
Fixes #222 

I tried to run RoslinPad.exe by specifying a .csx file in the command prompt. Please check.
Thanks:)

### CODE REVIEW

**Comment by aelij** [comment]
Thanks for the fix! But I have a few comments:

The code you added would run every time a new document is created. Instead, it needs to run once during initialization. I suggest adding another method called `OpenDocumentFromCommandLine` and invoke it from `InitializeInternal`, right before `OpenAutoSavedDocuments` (so it would appear as the first tab).

Also add a check if the file exists before opening it.

**Comment by ohadschn** [comment]
Theoretically speaking checking if the file doesn't exist [isn't enough, it has to be a try-catch](https://blogs.msdn.microsoft.com/ericlippert/2008/09/10/vexing-exceptions/).

Also I think `Environment.GetCommandLineArgs` elements can never be null.

**Comment by aelij** [comment]
Closing as there has been no reply to comments. You're welcome to address them and I'll reopen.

**Comment by jiyeongj** [comment]
I'm sorry I'm late.
I modified it according to your request.
Please reopen ! :)

**Comment by aelij** [comment]
@jiyeongj please push your changes

**Comment by jiyeongj** [comment]
https://github.com/jiyeongj/RoslynPad.git
I already pushed.
filechange seems to be invisible because the current issue is closed.

**Comment by aelij** [comment]
Thanks for the fix!

**Pull request merged**
