### PR TITLE
Fix MacOS unzip

### PR DESCRIPTION
**Pull request by gurgendav**
* Change "\\" (backslash) to "/" in path at the moment of creating .zip file to fix MacOS unzip issue

Fixes: #249

### CODE REVIEW

**Comment by aelij** [comment]
Thanks for the fix!

**Comment by phillijw** [comment]
Did this ever get released? Still having this same issue with the latest release (14.1)

**Comment by aelij** [comment]
@phillijw Not yet (you can check the release notes)

**Comment by lol768** [comment]
I just ran into this on Linux, too - would appreciate a new release

**Pull request merged**
