### PR TITLE
Added tabbed results for viewing as grid (current) or as text 

### PR DESCRIPTION
**Pull request by StingyJack**
Adds a tabbed results for grid and text.  Covers what I was asking about in #96 

image

image

### CODE REVIEW

**Comment by aelij** [comment]
Thank you for the contribution, @StingyJack, I really appreciate it. 

However, I'm afraid I don't see how this view is more useful than the current one. Your sample contains only simple strings. What would you show when a complex object is dumped?

Please understand that I'm trying very hard to keep RoslynPad's UI as simple and as uncluttered as possible. If you want to copy the entire result as a string, a button in the toolbar could provide this functionality.

In the future let's discuss such changes here so we can work together on the best approach.

**Comment by StingyJack** [comment]
I can't select just what I want from the grid based output. It's either all or one, and i need plain results far more often than a tabular set.

How does one emit output other than console/trace statements?

**Comment by SlowLogicBoy** [comment]
1. Right-click -> export output to file, which you can do yourself with File.WriteAllLines(...).
2. Some keyboard shortcut -> switches from one view to another, but this doesn't make it simpler UI
3. Run script in console instead of RoslynPad, by outputing content like in csi.exe?

**Comment by StingyJack** [comment]
@SlowLogicBoy - was that in response to the question of how to emit output or are those alternate implementations?

@aelij - I definitely dont want all the output, and after looking at the AvalonEdit, it would seem a better choice as it allows for columnar select, line numbering, etc and that avoids yet another potential step of copy/paste in another editor.

The primary use case for me is for quick ad-hoc scripts to do file parsing or other troubleshooting/analysis.  There are probably many of us that use these scripting environments (linqpad, scriptcs, etc) in this manner. The grid has two columns that will probably always be empty or not useful. I did poke a bit to find out how to toggle "flattening" the grid to a center column with selectable text, but WPF is new to me and that looked like more than I could handle on a Sunday morning. 

Since this program was useful to me, it seems appropriate to at least offer this PR in return, but its your program to maintain and your choice to incorporate it or not. (You'll get no grief from me if you choose "not").

**Comment by SlowLogicBoy** [comment]
@StingyJack - I just tried to think of alternative implementations, I think your PR is a good implementation and I would greatly benefit from it, but additional tab doesn't seem right for me at least.

**Comment by StingyJack** [comment]
https://github.com/aelij/RoslynPad/issues/101#issuecomment-298670957

```
c.DirectiveReferences
```

:lightbulb: ...so _thats_ why you want the grid.

**Comment by aelij** [comment]
@StingyJack  Oh, you've never used `Dump()` to view an entire object graph? Try `new Exception().Dump()`. If you end the script with an expression (like `c.DirectiveReferences`) i.e. without a semicolon, it also gets dumped.

**Pull request closed without merging**
