### PR TITLE
New execution host

### LINKED ISSUE #101: Is there a way to compile exe and copy all dependent dlls to output folder?
I'd like to be able to compile to exe (Which I realize is there), but copy all of the dlls to the folder where the exe was written.  Is there a way to currently do that?

Is there a way to use one of the RoslynPad libraries to load up a csx file, compile it to exe, and get a list of the dlls?  That would be another way I could get the result I'm looking for.

The reason I'm looking to do this, is that I've written a tool to parse LINQPad scripts, pull out all the references, and produce an exe file with all it's dlls.  That was alot of work though and I don't really want to do the same for RoslynPad, so I'm looking for an easier solution.

### PR DESCRIPTION
**Pull request by aelij**
This PR introduces a radically different `IExecutionHost` implementation `AssemblyExecutionHost`: instead of having a live "server" process for each document that accepts code to compile and run, RP compiles an EXE and runs it every time from disk. Output objects are delivered via `stdout` in JSON format. This means that RP processes are now very "pure". The only dependency is `RoslynPad.Common` which is a .NET Standard 2.0 assembly that has no other dependencies.

This aims to increase RP's compatibility with various libraries and scenarios. For example, there won't be a hard dependency on any assembly version that was used by the previous host (e.g. Newtonsoft.Json, Microsoft.CodeAnalysis, etc.) - it will mostly run *your* script code and a small bootstrapper that serializes dumped objects and exceptions. Also, getting a fresh process every run is much better IMO.

**I invite you to test it out.** Note it's still "alpha" - threre's no handling of assembly loading for example, so `#r` for local files won't work. This will be fixed before this feature is released.

Also fixes #101

### CODE REVIEW

**Comment by ohadschn** [comment]
I guess this also means our code won't be running on a UI thread? Would also be a win IMO...

**Comment by aelij** [comment]
The UI thread is a "feature" :) I think running single-threaded it can simplify a few scenarios (less chance of races), which might be why Roslyn's C# Interactive works this way. I can actually still support it by installing a sync context during init.

What's so bad about it? Forgetting `ConfigureAwait` can be a bug waiting to happen... :P

**Comment by ohadschn** [comment]
The way I use and view RP (and I suspect the vast majority of people) is as a quick and lightweight alternative to a VS C# console project, where I can just write some code and execute it real fast. If that code doesn't work for whatever reason that isn't easily apparent, I'm going to paste that code in a VS console app, and if it works there I'm going to assume it's some sort of issue in the way RP executes code - after all, it works just fine in VS right? I would then either report the issue or decide to use RP less because I don't trust it (even if I'm at fault, e.g. for forgetting `ConfigureAwait`).

IMHO this PR seems to go in a great direction, and installing some hidden SC during init would defeat the purpose. Besides, which SC would you install - WPF? What if I want to use WF or some other technology? Same questions about the assemblies you'd reference. And you'd have to make the thread `STA`, potentially creating differences far beyond the debugging ability of most devs.

Having said that, an optional feature like "run in WPF" context could be really cool (where you'd reference `presentationframework.dll`, make the thread STA, install the WPF SC, etc), as long as it's not the default.

**Comment by aelij** [comment]
> which SC would you install?

Same as today, WPF for .NET Desktop, and Toub's `SingleThreadSynchronizationContext` for Core. Or perhaps Avalonia's.

> What if I want to use WF

It would still work. The underline native API (i.e. message pump) is the same.

But I get your point, this could be configurable. It's a breaking change though - lots of RP users build UI elements and without a message loop they'd have to change their code.

Maybe I'll add an API, such as `await SwitchToUIThread();`.

**Comment by ohadschn** [comment]
Interesting that  `DispatcherSynchronizationContext` would work for WF, but surely there is a reason those are two different classes with what appear to be very different implementations? 

I appreciate that the underlying message pump is the same WIN32 mechanism but certainly there are layers on top of it? For example maybe the shutdown mechanism works a little different so something like this could introduce weird bugs?

**Comment by aelij** [comment]
It's a fully supported scenario and was designed for it -- you can host WPF in WF and vice versa, and there can be only one message pump per thread.

**Comment by aelij** [comment]
Another nice advantage is that you get a directory with built executables you can just copy and use. It also handles dependencies (which was quite a bit of work to get right without using MSBuild...)

```csharp
#r "nuget:Newtonsoft.Json/12.0.1"

using System.Runtime.InteropServices;

RuntimeInformation.FrameworkDescription.Dump();

Newtonsoft.Json.JsonConvert.SerializeObject(new { A = 1 }).Dump();
```
Run from shell:
```
PS> dotnet .\RoslynPad-Program1.dll
{"Children":null,"Header":null,"IsExpanded":true,"Type":"String (System)","Value":".NET Core 4.6.27317.07"}
{"Children":null,"Header":null,"IsExpanded":true,"Type":"String (System)","Value":"{\"A\":1}"}
```

**Comment by aelij** [comment]
Getting there....

TODO:
- [ ] Fix exception results
- [ ] Support for non-NuGet `#r` in .NET Core (add to depsfile)
- [ ] Do not copy NuGet references in .NET Core

**Pull request merged**
